### ISSUE TITLE
Python: missing requirement wheel for hidapi

### ISSUE THREAD

**Issue by AdamN1** [dgomes/dali2mqtt#11]
Hi,
python-dali==0.7 intalled from pip requires hidapi packages, log from console: https://pastebin.com/Ub0NepZf

_pip install hidapi_ requires headers for: libusb, libudev
On debian like system we can install them by _apt-get install libusb-1.0-0-dev libudev-dev_

**Comment by kbacia7** [comment]
It's added, we can close this issue? (#18)

**Comment by dgomes** [comment]
We have the requirement but we don't have a wheel... many people will fail to install without the deepen
