### ISSUE TITLE
Add firmware check of hasseb device with restriction to version number(version??)

### ISSUE THREAD

**Issue by AdamN1** [dgomes/dali2mqtt#12]
Hi,
Current version 0.7 of python-dali require new firmware.
We can add firmware version check for hasseb driver with information about upgrade and link redirection.

@dgomes what you about this? 
If you are ok with this we(@JustNet) can prepare patch with PR.

**Comment by dgomes** [comment]
Go ahead! :)

**Comment by kbacia7** [comment]
Done in #25
