### ISSUE TITLE
Query device about physical minimum/max brightness level and propagate information to HA

### ISSUE THREAD

**Issue by AdamN1** [dgomes/dali2mqtt#13]
Hi,
DALI device can inform about supported minimum/max brightness level. At initialization level of dali2mqtt we can ask every device about minimum/max brightness level and send information via MQTT to HA.

DALI supported commands: **Query Physical Minimium**, **Query Max Level**, **Query Min Level**

@dgomes what you about this?
If you are ok with this we(@JustNet) can prepare patch with PR.

**Comment by kbacia7** [comment]
Here is missing one information. I should send this to MQTT with some strict imposed topic for HA?

**Comment by dgomes** [comment]
HA doesn't have the concept of Physical Min, Max/Min Level 

but I propose:

lamp/N/physical_minimum
lamp/N/max_level
lamp/N/min_level

**Comment by kbacia7** [comment]
Merged in #34
