### ISSUE TITLE
Don't overwrite config file after each run

### ISSUE THREAD

**Issue by AdamN1** [dgomes/dali2mqtt#15]
Script when closing alway overwrite config file with setting fetched on start. 
This create situation where we can't change configuration without exiting script. Better aproache is to read file at startut, and don't override on exiting.

**Comment by dgomes** [comment]
this behaviour is very similar to zigbee2mqtt, my intention was to eventually provide MQTT topics to change the configuration on the fly...

**Comment by AdamN1** [comment]
> this behaviour is very similar to zigbee2mqtt, my intention was to eventually provide MQTT topics to change the configuration on the fly...

Will HA have support for this or do you like to change configuration from separate mqtt client?

**Comment by dgomes** [comment]
> Will HA have support for this or do you like to change configuration from separate mqtt client?

you can have both way :)

**Comment by AdamN1** [comment]
I come with proposition to resolve the case:
1. script don't overwrite configuration on closing
2. MQTT, introduction of new functions to work with config:
   - mqtt_config_read(variable) - will return config variable or all variable when variable is empty
   - mqtt_config_set(variable,value) - will set variable to value
   - mqtt_config_commit - will commit changes to config file

In separate ticket we can add check if the config file didn't change after first run. If file was changed we block commit of config variable. 

@dgomes what you think?

**Comment by dgomes** [comment]
you don't need those many functions... I'll put in a PR with an example of what makes since to me

**Comment by AdamN1** [comment]
> you don't need those many functions... I'll put in a PR with an example of what makes since to me

@dgomes Can you give some example so we can start working on this?

**Comment by dgomes** [comment]
I've already started a new configuration class to handle this, hope to finish it soon

**Comment by dgomes** [comment]
@kbacia7 please test and check if we can close this

**Comment by kbacia7** [comment]
Tested on newest `master`, works
