### ISSUE TITLE
Adding color support for the system log

### ISSUE THREAD

**Issue by AdamN1** [dgomes/dali2mqtt#16]
Adding color support for the system log like:

- error - red
- notice - default
- information status (ok) - green
- information status (bad) - red

**Comment by dgomes** [comment]
as long as it still uses python logging, is optional and off by default I'm OK

**Comment by AdamN1** [comment]
> as long as it still uses python logging, is optional and off by default I'm OK

@dgomes Is there a way to convince you to turn on by default log coloring(red) for 'errors' ?
I think today all terminals support coloring so it shouldn't be a issue.

**Comment by AdamN1** [comment]
I only want to color console output on the terminal.
Maybe we can implement something like -F --foreground with color on?

**Comment by dgomes** [comment]
that is acceptable

(please use separate PR's for each issue)

**Comment by dgomes** [comment]
closed by #22
