### ISSUE TITLE
Fix max lamp implementation vs DALI range

### ISSUE THREAD

**Issue by AdamN1** [dgomes/dali2mqtt#17]
Hi,
In script we can set dali-lamps number but latter this map to max_range which is responsible for limiting the addresses to be searched. I think that implementation is wrong. Let's assume situation with four lamps:

1. lamp 1 address 0
2. lamp 2 address 2
3. lamp 3 address 4
4. lamp 4 address 6
In the current implementation script will find only the first two lamps.

I think that we need to separate number of lamps from dali address range. This will allow people to use non continuous address number for the lamps.

**Comment by dgomes** [comment]
(please translate)

**Comment by AdamN1** [comment]
Fixed :D

**Comment by AdamN1** [comment]
@dgomes I think that PR #21 should be rejected and let's start second  new clean approach on new PR.

I think PR should address the problems:

1. adding support for an address range (dali short address) to be searched, what you think about variable name: --dali-shortaddress-range -dsr?
2. stop search when --dali-lamps is meet, what you think about rename this to --dali_lamps_number -dln?

AD.1 variable --dali-shortaddress-range -dsr should support:

- range like 5-12 - search short address from 5 to 12
- name full - full search of dali range from 0 to 63, default option

**Comment by AdamN1** [comment]
@dgomes are you ok with my proposal? If you are ok, we can start work on this.

**Comment by dgomes** [comment]
Actually since the new firmware was release, this initial scan (which used to take several seconds) is now very fast. 

Maybe we can simply remove this option and always scan all the addresses ?

**Comment by AdamN1** [comment]
I don't see any harm in adding this. If someone want to scan only part of dali short range let's give them this possibility.
If scanning speed isn't issue now, let's make default to scan full range, ok?

**Comment by dgomes** [comment]
Lets go full range!

**Comment by AdamN1** [comment]
> Lets go full range!

So we delete **dali-lamps** and set range 0,63 without options to customize, yes?
