### ISSUE TITLE
Add support for --log-level

### ISSUE THREAD

**Issue by AdamN1** [dgomes/dali2mqtt#19]
Add new option with ability to set log level. 
Option will help to switch from info to debug level without changing the source code

The idea proposed by @kbacia7 in [message](https://github.com/dgomes/dali2mqtt/pull/18#discussion_r481975584)

**Comment by dgomes** [comment]
closed by #18

**Comment by AdamN1** [comment]
@dgomes can we merge this?

**Comment by dgomes** [comment]
The current version already has this right ?

**Comment by AdamN1** [comment]
I had to miss the PR, so we can close this ticket, yes?
