### ISSUE TITLE
Periodicaly scan of new lamps - adding new lamps without restart

### ISSUE THREAD

**Issue by AdamN1** [dgomes/dali2mqtt#29]
I think it will be nice addition. It's not very important but nice.
We can also use mqtt to trigger scan.

**Comment by dgomes** [comment]
I think an MQTT trigger is more appropriate

**Comment by kbacia7** [comment]
We want to scan for new lamps when dali2mqtt receive some topic, yes?

**Comment by kbacia7** [comment]
Do you have any idea how I can detect turning on a lamp on the DALI bus when a script is turned on (runtime) and the lamp was previous turned off? 
@dgomes

**Comment by dgomes** [comment]
not sure I understand
