### ISSUE TITLE
dali2mqtt reset config to default values

### ISSUE THREAD

**Issue by kbacia7** [dgomes/dali2mqtt#32]
After lasts commits to master branch, running dali2mqtt resets `config.yaml` to default settings, in results, changing any of config values doesn't take effect.

To reproduce:
1. Change `mqtt_server` in `config.yaml`
2. Run dali2mqtt
3. In new terminal window look at `config.yaml`, `mqtt_server` is `localhost` 

And last, we wanna change `config.yaml` based on arguments passed to script? I always had feeling that passing parameters to scripts via arguments (like `--mqtt-server`) is for temporialy changing this value, not save new value to configuration

**Comment by dgomes** [comment]
check my latests commit

**Comment by kbacia7** [comment]
All works on `master`
