### ISSUE TITLE
Brightness levels based on real data

### ISSUE THREAD

**Issue by kbacia7** [dgomes/dali2mqtt#36]
After #13 we can set `brightness_scale` in HA config for devices, based on real `max_level`.
Change brightness level can now support levels from `min_level` to `max_level`
And I think that maybe I should add class to represent DALI Lamps as objects and store collected data? For better reading code and more OOP way

**Comment by kbacia7** [comment]
@dgomes Psst, I edited comment after you give ":+1:", lemme know what do you think about it:
> And I think that maybe I should add class to represent DALI Lamps as objects and store collected data? For better reading code and more OOP way

**Comment by dgomes** [comment]
Creating Lamp class makes sense, HA discovery logic should also be moved into that class
