### ISSUE TITLE
pyusb requirement

### ISSUE THREAD

**Issue by beireken** [dgomes/dali2mqtt#4]
Pyusb is a dependency for pyusb, it seems as though this is preinstalled on most systems, though not al.
Maybe add it to the requirements.txt?

`pyusb==1.0.2`

**Comment by dgomes** [comment]
curiously that should be a requirement of python-dali, this program does not depend per si of USB

**Comment by beireken** [comment]
i doesn't come installed through pip with python-dali though. Had to install manually.

**Comment by dgomes** [comment]
I understand that, but logically this issue should be added to the python-dali project
