### ISSUE TITLE
Bug in device name

### ISSUE THREAD

**Issue by Pshatsillo** [dgomes/dali2mqtt#56]
This line https://github.com/dgomes/dali2mqtt/blob/05d18eb60ab11b8b03c2f9f43d4d4cfd2c046aef/lamp.py#L43 on Python 3.9.2  should change to `self.device_name = slugify(str(friendly_name))`. Could you please fix it?

**Comment by dgomes** [comment]
when is friendly_name not a string ??

**Comment by Pshatsillo** [comment]
for example when dali_server used it`s integer

**Comment by Pshatsillo** [comment]
Thank you!
