### ISSUE TITLE
mqtt topics

### ISSUE THREAD

**Issue by dz3022** [dgomes/dali2mqtt#67]
Hello,
I installed dali2mqtt and it is up and running. It detects my Dali USB-HID device and one fixture named "philips"
I want to use this software without Home Assistant. I am running Node-RED with an MQTT broker, but I am unsure which MQTT topics I should use.

The topic dali2mqtt/status works and provides the output "online" but I have tried for instance: dali2mqtt/philips/light/status without any response.
Can you please list the MQTT topics that can be used? Thanks.

**Comment by dgomes** [comment]
Well spot!

I've created: https://github.com/dgomes/dali2mqtt/wiki/MQTT-Topics
